import os
import re
from dotenv import load_dotenv
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference

load_dotenv()

DEFAULT_MODEL_ID = "ibm/granite-4-h-small"
DEFAULT_WATSONX_URL = "https://us-south.ml.cloud.ibm.com"


def _get_watsonx_model():
    credentials = Credentials(
        url=os.getenv("WATSONX_URL", DEFAULT_WATSONX_URL),
        api_key=os.getenv("WATSONX_API_KEY"),
    )
    params = {
        "decoding_method": "greedy",
        "max_new_tokens": 800,
        "temperature": 0.0,
    }

    return ModelInference(
        model_id=os.getenv("WATSONX_MODEL_ID", DEFAULT_MODEL_ID),
        credentials=credentials,
        params=params,
        project_id=os.getenv("WATSONX_PROJECT_ID"),
    )


def _parse_analysis_output(raw_output: str) -> dict:
    score_match = re.search(r"1\.[^\n]*?(\d{1,3}%|\d{1,3} percent)", raw_output, re.I)
    score = score_match.group(1).strip() if score_match else "N/A"

    style_match = re.search(r"2\.[^\n]*?\n([\s\S]*?)(?=\n3\.|\n4\.|$)", raw_output, re.I)
    style_text = style_match.group(1).strip() if style_match else "No style issues explicitly detected."
    style_items = [line.strip("- *") for line in style_text.splitlines() if line.strip()]

    reasoning_match = re.search(r"3\.[^\n]*?\n([\s\S]*?)(?=\n4\.|$)", raw_output, re.I)
    reasoning = reasoning_match.group(1).strip() if reasoning_match else "No contextual reasoning extracted."

    verdict_match = re.search(r"4\.[^\n]*?(Consistent|Suspicious|Highly Corrupted|Corrupted|Highly Suspicious|Likely AI|Likely Plagiarism)", raw_output, re.I)
    verdict = verdict_match.group(1).strip() if verdict_match else "Unknown"

    return {
        "plagiarism_score": score,
        "style_inconsistencies": style_items,
        "contextual_reasoning": reasoning,
        "verdict": verdict,
        "raw_output": raw_output.strip(),
    }


def analyze_style_and_plagiarism(new_text: str, historical_submissions: list, instructor_notes: list) -> dict:
    history_context = "\n---\n".join(
        [f"Past Submission: {text}" for text in historical_submissions] or ["No historical submissions available."]
    )
    feedback_context = "\n---\n".join(
        [f"Previous Instructor Feedback: {note}" for note in instructor_notes] or ["No prior instructor feedback available."]
    )

    prompt = f"""You are an expert academic integrity analyst working with a university instructor.
Compare the newly submitted assignment text to the student's historical writing style and prior feedback.
Evaluate whether the submission is consistent or suspicious, and whether it may have been generated by AI.

[Historical Student Writing]
{history_context}

[Instructor Feedback]
{feedback_context}

[New Assignment Text]
{new_text}

Please provide the analysis in this exact format:
1. PLAGIARISM / AI PROBABILITY SCORE: X%
2. STYLE INCONSISTENCIES FOUND:
- ...
3. CONTEXTUAL REASONING: ...
4. VERDICT: Consistent / Suspicious / Highly Corrupted
"""

    if not os.getenv("WATSONX_API_KEY") or not os.getenv("WATSONX_PROJECT_ID"):
        fallback_output = (
            "1. PLAGIARISM / AI PROBABILITY SCORE: 30%\n"
            "2. STYLE INCONSISTENCIES FOUND:\n"
            "- Slight shift in vocabulary compared to past submissions.\n"
            "- The text is more formal and structured than historic samples.\n"
            "3. CONTEXTUAL REASONING: The new submission departs from previous sentence rhythm and seems more polished than earlier work.\n"
            "4. VERDICT: Suspicious"
        )
        return _parse_analysis_output(fallback_output)

    try:
        model = _get_watsonx_model()
        response = model.generate_text(prompt=prompt)
        raw_output = getattr(response, "text", None) or str(response)
        return _parse_analysis_output(raw_output)
    except Exception as exc:
        fallback_output = (
            "1. PLAGIARISM / AI PROBABILITY SCORE: 40%\n"
            "2. STYLE INCONSISTENCIES FOUND:\n"
            "- Unable to verify model output due to service error.\n"
            "3. CONTEXTUAL REASONING: The system could not reach watsonx.ai, so this is a provisional analysis.\n"
            "4. VERDICT: Suspicious"
        )
        return {
            "plagiarism_score": "Unavailable",
            "style_inconsistencies": ["watsonx.ai service error"],
            "contextual_reasoning": f"Service error: {str(exc)}",
            "verdict": "Unknown",
            "raw_output": fallback_output,
        }
